# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI1_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 80, 201, 311))
        self.groupBox.setObjectName("groupBox")
        self.btn_load_image_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_load_image_1.setGeometry(QtCore.QRect(60, 50, 75, 23))
        self.btn_load_image_1.setObjectName("btn_load_image_1")
        self.btn_load_image_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_load_image_2.setGeometry(QtCore.QRect(60, 110, 75, 23))
        self.btn_load_image_2.setObjectName("btn_load_image_2")
        self.btn_keypoints = QtWidgets.QPushButton(self.groupBox)
        self.btn_keypoints.setGeometry(QtCore.QRect(60, 170, 75, 23))
        self.btn_keypoints.setObjectName("btn_keypoints")
        self.btn_matched_keypoints = QtWidgets.QPushButton(self.groupBox)
        self.btn_matched_keypoints.setGeometry(QtCore.QRect(40, 240, 121, 21))
        self.btn_matched_keypoints.setObjectName("btn_matched_keypoints")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "4. SIFT"))
        self.btn_load_image_1.setText(_translate("MainWindow", "Load Image 1"))
        self.btn_load_image_2.setText(_translate("MainWindow", "Load Image 2"))
        self.btn_keypoints.setText(_translate("MainWindow", "4.1Keypoints"))
        self.btn_matched_keypoints.setText(_translate("MainWindow", "4.2Matched Keypoimts"))
